"""Application core abstractions and runtime services."""

from .context import AppContext, create_app_context
from .controllers import (
    QuickWriteController,
    StartupDeviceRestoreController,
    StartupUpdateController,
)
from .device_identity import (
    format_checksum_type_name,
    generic_ipod_image_filename,
    identify_ipod_at_root,
    refresh_device_disk_usage,
    resolve_device_image_filename,
    resolve_ipod_image_color,
    resolve_ipod_product_image_filename,
)
from .dropped_files import (
    DroppedImportFiles,
    collect_import_file_paths,
    collect_media_file_paths,
    is_media_drop_candidate,
)
from .errors import AppConfigurationError, AppError, AppStateError, BackgroundJobError
from .jobs import (
    BackSyncRequest,
    BackSyncWorker,
    BackupCreateRequest,
    BackupCreateWorker,
    BackupDeviceContext,
    BackupDeviceInventory,
    BackupRestoreRequest,
    BackupRestoreWorker,
    BackupSnapshotCatalog,
    DeviceScanWorker,
    SyncToolAvailability,
    ToolDownloadWorker,
    backup_device_name_from_playlists,
    build_backup_device_context,
    build_backup_device_meta,
    build_imported_photo_edit_state,
    build_podcast_plan_for_sync,
    check_sync_tool_availability,
    delete_backup_snapshot,
    ensure_backup_folder,
    list_backup_devices_for_view,
    load_backup_snapshot_catalog,
    scan_for_ipod_devices,
)
from .services import (
    DeviceCapabilitySnapshot,
    DeviceIdentitySnapshot,
    DeviceManagerLike,
    DeviceSession,
    DeviceSessionService,
    DeviceStorageSnapshot,
    LibraryCacheLike,
    LibraryService,
    LibrarySnapshot,
    SettingsService,
    SettingsSnapshot,
)
from .sync_plan_builder import build_removal_sync_plan
from .sync_session import (
    PodcastPlanningInput,
    SyncExecutionIntent,
    SyncPlanningIntent,
    SyncSessionBlocked,
    SyncSessionController,
    SyncSessionMissingTools,
)

__all__ = [
    "AppConfigurationError",
    "AppContext",
    "AppError",
    "AppStateError",
    "BackgroundJobError",
    "BackupCreateRequest",
    "BackupCreateWorker",
    "BackupDeviceContext",
    "BackupDeviceInventory",
    "BackupRestoreRequest",
    "BackupRestoreWorker",
    "BackupSnapshotCatalog",
    "BackSyncRequest",
    "BackSyncWorker",
    "DeviceScanWorker",
    "DroppedImportFiles",
    "DeviceSession",
    "DeviceCapabilitySnapshot",
    "DeviceIdentitySnapshot",
    "DeviceManagerLike",
    "DeviceSessionService",
    "DeviceStorageSnapshot",
    "format_checksum_type_name",
    "generic_ipod_image_filename",
    "identify_ipod_at_root",
    "LibraryCacheLike",
    "LibraryService",
    "LibrarySnapshot",
    "PodcastPlanningInput",
    "QuickWriteController",
    "SettingsService",
    "SettingsSnapshot",
    "StartupDeviceRestoreController",
    "StartupUpdateController",
    "refresh_device_disk_usage",
    "resolve_device_image_filename",
    "resolve_ipod_image_color",
    "resolve_ipod_product_image_filename",
    "SyncExecutionIntent",
    "SyncPlanningIntent",
    "SyncSessionBlocked",
    "SyncSessionController",
    "SyncSessionMissingTools",
    "SyncToolAvailability",
    "ToolDownloadWorker",
    "backup_device_name_from_playlists",
    "build_backup_device_context",
    "build_backup_device_meta",
    "build_imported_photo_edit_state",
    "build_podcast_plan_for_sync",
    "build_removal_sync_plan",
    "check_sync_tool_availability",
    "collect_import_file_paths",
    "collect_media_file_paths",
    "create_app_context",
    "delete_backup_snapshot",
    "ensure_backup_folder",
    "is_media_drop_candidate",
    "list_backup_devices_for_view",
    "load_backup_snapshot_catalog",
    "scan_for_ipod_devices",
]
